INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (6, 'Estanteria con puertas', 60.00, 'Estanteria con puertas de madera de color negro y marron', 'Moderno', '6.jpg', 2);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (7, 'Lampara de mesa', 10.50, 'Lampara de mesa con iluminacion amarilla', 'Vintage', '7.jpg', 1);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (8, 'Alfombra de salon', 49.99, 'Alfombra de salon de color azul y marron', 'Minimalista', '8.jpg', 4);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (9, 'Bandeja de madera', 12.90, 'Bandeja de madera anticuada de color marron', 'Anticuado', '9.jpg', 3);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (10, 'Expositor de gafas', 6.90, 'Expositor de gafas de madera transparente', 'Contemporaneo', '10.jpg', 5);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (11, 'Jarrones modernos', 30.20, 'Jarrones modernos de color blanco, azul y marron', 'Moderno', '11.jpg', 3);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (12, 'Funda de edredon', 25.50, 'Funda de edredon de estilo vintage', 'Vintage', '12.jpg', 4);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (13, 'Organizador de joyas', 45.50, 'Organizador de joyas de color azul', 'Minimalista', '13.jpg', 5);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (14, 'Lampara de pie', 15.00, 'Lampara de pie de estilo antguo de color blanco', 'Anticuado', '14.jpg', 1);
INSERT INTO products (id, name, price, description, style, image, category_id) VALUES (15, 'Mueble para TV', 99.99, 'Mueble para TV de estilo contemporaneo, blanco con puertas de madera', 'Contemporaneo', '15.jpg', 2);
