INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (95, 'Cama doble', 'Cama doble con cabecero tapizado', 350.00, 'Moderno', '95.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (96, 'Cabecero madera', 'Cabecero de madera rústica', 90.00, 'Rustico', '96.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (97, 'Mesita de noche', 'Mesita de noche con dos cajones', 45.00, 'Minimalista', '97.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (98, 'Banco pie de cama', 'Banco tapizado para pie de cama', 70.00, 'Clasico', '98.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (99, 'Tocador con espejo', 'Tocador blanco con espejo y taburete', 120.00, 'Vintage', '99.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (100, 'Estantería pared', 'Estantería flotante de madera', 25.00, 'Nordico', '100.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (101, 'Escritorio dormitorio', 'Escritorio compacto para dormitorio', 85.00, 'Moderno', '101.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (102, 'Banco almacenaje', 'Banco baúl para guardar ropa', 65.00, 'Funcional', '102.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (103, 'Lámpara mesita', 'Lámpara de noche con luz cálida', 20.00, 'Calido', '103.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (104, 'Cadena luz decorativa', 'Guirnalda de luces LED para cabecero', 12.00, 'Decorativo', '104.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (105, 'Lámpara cargador', 'Lámpara con cargador inalámbrico', 35.00, 'Tecnologico', '105.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (106, 'Luz nocturna', 'Luz quitamiedos para enchufe', 8.00, 'Infantil', '106.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (107, 'Luz colores LED', 'Bombilla LED con cambio de color', 15.00, 'Moderno', '107.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (108, 'Panel techo regulable', 'Plafón LED con intensidad regulable', 45.00, 'Minimalista', '108.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (109, 'Luz ambiental', 'Lámpara de suelo para luz indirecta', 55.00, 'Zen', '109.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (110, 'Luz lectura', 'Flexo pinza para leer en cama', 12.00, 'Funcional', '110.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (111, 'Lámpara de pie', 'Lámpara alta para rincón de lectura', 60.00, 'Clasico', '111.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (112, 'Lámpara techo tela', 'Lámpara colgante con pantalla textil', 40.00, 'Textil', '112.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (113, 'Set cuadros dormitorio', 'Tríptico de cuadros relajantes', 30.00, 'Zen', '113.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (114, 'Reloj despertador', 'Reloj de mesa estilo vintage', 15.00, 'Vintage', '114.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (115, 'Espejo de pie', 'Espejo de cuerpo entero marco madera', 70.00, 'Rustico', '115.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (116, 'Jarrones cerámica', 'Juego de jarrones decorativos', 22.00, 'Artesanal', '116.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (117, 'Almohadas decorativas', 'Cojines pequeños para la cama', 12.00, 'Textil', '117.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (118, 'Figuras decorativas', 'Escultura moderna pequeña', 18.00, 'Moderno', '118.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (119, 'Frases pared', 'Vinilo decorativo con frase', 10.00, 'Inspiracional', '119.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (120, 'Planta interior', 'Planta artificial realista', 25.00, 'Natural', '120.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (121, 'Portafolios', 'Marco para fotos sobremesa', 8.00, 'Clasico', '121.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (122, 'Juego sábanas', 'Sábanas de algodón 100% suaves', 35.00, 'Suave', '122.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (123, 'Edredón nórdico', 'Edredón cálido para invierno', 60.00, 'Invierno', '123.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (124, 'Funda almohada', 'Pareja de fundas de almohada satén', 15.00, 'Elegante', '124.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (125, 'Cortinas dormitorio', 'Cortinas largas de lino', 40.00, 'Natural', '125.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (126, 'Alfombra pie cama', 'Alfombra de pelo largo suave', 28.00, 'Diseno', '126.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (127, 'Cubrecolchón', 'Protector de colchón impermeable', 22.00, 'Funcional', '127.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (128, 'Manta lectura', 'Manta de sofá o cama muy suave', 18.00, 'Confort', '128.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (129, 'Cortinas Blackout', 'Cortinas opacas para bloquear luz', 45.00, 'Oscuro', '129.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (130, 'Plaid pie cama', 'Manta decorativa para los pies', 20.00, 'Decorativo', '130.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (131, 'Cajas bajo cama', 'Cajas con ruedas para almacenar', 18.00, 'Plastico', '131.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (132, 'Separador armario', 'Organizadores de tela para estantes', 12.00, 'Tela', '132.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (133, 'Perchero de pie', 'Perchero para ropa del día siguiente', 35.00, 'Madera', '133.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (134, 'Ganchos puerta', 'Colgador para detrás de la puerta', 8.00, 'Metal', '134.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (135, 'Cajas zapatos', 'Cajas transparentes apilables', 5.00, 'Acrilico', '135.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (136, 'Estantes modulares', 'Cubos organizadores para ropa', 25.00, 'Modular', '136.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (137, 'Bandeja vaciabolsillos', 'Bandeja para mesita de noche', 10.00, 'Cuero', '137.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (138, 'Caja fuerte', 'Pequeña caja fuerte doméstica', 50.00, 'Seguridad', '138.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (139, 'Aroma ropa cajones', 'Sobres perfumados para armarios', 6.00, 'Fresco', '139.jpg', 6);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (140, 'Ambientador textil', 'Spray para sábanas y cortinas', 9.00, 'Lavanda', '140.jpg', 6);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (141, 'Cuna madera', 'Cuna de madera blanca', 120.00, 'Clasico', '141.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (142, 'Cambiador bebé', 'Mueble cambiador con cajones', 95.00, 'Funcional', '142.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (143, 'Móvil musical', 'Móvil giratorio para cuna', 25.00, 'Musical', '143.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (144, 'Ropa de cuna', 'Juego de sábanas para cuna', 20.00, 'Suave', '144.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (145, 'Edredón bebé', 'Edredón ligero infantil', 28.00, 'Calido', '145.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (146, 'Manta polar bebé', 'Manta extra suave para bebé', 15.00, 'Polar', '146.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (147, 'Protector enchufes', 'Pack seguridad enchufes', 5.00, 'Seguridad', '147.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (148, 'Organizador ropa bebé', 'Separadores para ropa pequeña', 12.00, 'Practico', '148.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (149, 'Cierres seguridad', 'Bloqueo para cajones y puertas', 8.00, 'Seguridad', '149.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (150, 'Termómetro habitación', 'Termómetro digital ambiente', 14.00, 'Tecnologico', '150.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (151, 'Silla colgante', 'Silla huevo colgante para terraza', 180.00, 'Boho', '151.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (152, 'Mesa auxiliar exterior', 'Mesita resistente al agua', 40.00, 'Metal', '152.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (153, 'Alfombra balcón', 'Alfombra exterior pequeña', 25.00, 'Exterior', '153.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (154, 'Cojines exterior', 'Cojines impermeables', 15.00, 'Resistente', '154.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (155, 'Luz ambiental jardín', 'Bolitas de luz solar', 18.00, 'Solar', '155.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (156, 'Hamaca', 'Hamaca de tela colgante', 35.00, 'Relax', '156.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (157, 'Maceta grande', 'Macetero decorativo exterior', 22.00, 'Ceramica', '157.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (158, 'Cortina exterior', 'Cortina parasol para pérgola', 30.00, 'Blanco', '158.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (159, 'Puf exterior', 'Puf impermeable tipo pera', 50.00, 'Comodo', '159.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (160, 'Mini nevera exterior', 'Nevera eléctrica portátil', 80.00, 'Tecnologico', '160.jpg', 8);
