INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (161, 'Mueble lavabo', 'Mueble de madera para lavabo con cajones', 180.00, 'Moderno', '161.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (162, 'Armario baño pared', 'Armario colgante con espejo', 90.00, 'Funcional', '162.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (163, 'Estantería bambú', 'Estantería de pie hecha de bambú', 45.00, 'Natural', '163.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (164, 'Banco de teca', 'Banco resistente al agua para ducha', 75.00, 'Spa', '164.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (165, 'Espejo marco negro', 'Espejo redondo con marco industrial', 60.00, 'Industrial', '165.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (166, 'Carrito auxiliar', 'Carrito metalico con ruedas', 30.00, 'Practico', '166.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (167, 'Repisa flotante', 'Pequeña repisa para cosméticos', 15.00, 'Minimalista', '167.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (168, 'Gabinete inodoro', 'Mueble para salvar el inodoro', 55.00, 'AhorraEspacio', '168.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (169, 'Tocador maquillaje', 'Pequeño tocador para baño', 110.00, 'Chic', '169.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (170, 'Cesta ropa sucia', 'Cesta de mimbre con tapa', 25.00, 'Rustico', '170.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (171, 'Aplique LED espejo', 'Luz frontal para espejo de baño', 35.00, 'Moderno', '171.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (172, 'Luz empotrada ducha', 'Foco LED impermeable IP65', 18.00, 'Tecnico', '172.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (173, 'Luz regulable baño', 'Plafón con intensidad ajustable', 45.00, 'Funcional', '173.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (174, 'Foco tocador', 'Luces estilo camerino', 40.00, 'Vintage', '174.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (175, 'Lámpara techo baño', 'Lámpara resistente a la humedad', 30.00, 'Clasico', '175.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (176, 'Espejito con luz', 'Espejo de aumento con luz LED', 25.00, 'Practico', '176.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (177, 'Lámpara impermeable', 'Lámpara flotante para bañera', 20.00, 'Relax', '177.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (178, 'Luz armario sensor', 'Luz para interior mueble baño', 12.00, 'Tecnologico', '178.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (179, 'Luz nocturna WC', 'Luz tenue para el inodoro', 10.00, 'Divertido', '179.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (180, 'Tira LED impermeable', 'Tira LED siliconada para ducha', 22.00, 'Moderno', '180.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (181, 'Cuadros botánicos', 'Láminas resistentes humedad', 20.00, 'Natural', '181.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (182, 'Planta colgante', 'Helecho artificial realista', 15.00, 'Verde', '182.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (183, 'Porta cepillos', 'Vaso cerámica para cepillos', 12.00, 'Ceramica', '183.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (184, 'Alfombra baño deco', 'Alfombra estampada antideslizante', 18.00, 'Boho', '184.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (185, 'Cestas almacenaje', 'Set de cestas de junco', 25.00, 'Natural', '185.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (186, 'Porta jabón', 'Jabonera de piedra natural', 14.00, 'Zen', '186.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (187, 'Dispensador jabón', 'Dispensador automático sensor', 22.00, 'Tecnologico', '187.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (188, 'Bandeja organizadora', 'Bandeja efecto mármol', 16.00, 'Elegante', '188.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (189, 'Altavoz ducha', 'Altavoz bluetooth impermeable', 30.00, 'Divertido', '189.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (190, 'Botes cristal', 'Botes para algodones y sales', 10.00, 'Clasico', '190.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (191, 'Juego toallas baño', 'Juego toallas algodón egipcio', 45.00, 'Suave', '191.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (192, 'Toallas manos', 'Set de 2 toallas de mano', 15.00, 'Basico', '192.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (193, 'Toallas pequeñas', 'Pack toallitas faciales', 12.00, 'Practico', '193.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (194, 'Cortina ducha', 'Cortina tejido repelente agua', 20.00, 'Moderno', '194.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (195, 'Paños faciales', 'Paños microfibra limpieza cara', 8.00, 'Beauty', '195.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (196, 'Toalla microfibra', 'Toalla secado rápido pelo', 10.00, 'Funcional', '196.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (197, 'Albornoz unisex', 'Albornoz rizo algodón', 35.00, 'Confort', '197.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (198, 'Guante exfoliante', 'Guante de crin natural', 6.00, 'Spa', '198.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (199, 'Esponja natural', 'Esponja marina natural', 12.00, 'Ecologico', '199.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (200, 'Cubre inodoro', 'Funda acolchada para tapa WC', 9.00, 'Calido', '200.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (201, 'Estante ducha', 'Estante colgar sin taladro', 18.00, 'Inox', '201.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (202, 'Canasta ducha', 'Cesta plástica con agujeros', 8.00, 'Basico', '202.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (203, 'Soporte secador', 'Soporte pared para secador pelo', 12.00, 'Metal', '203.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (204, 'Bandeja giratoria', 'Organizador giratorio cosméticos', 20.00, 'Acrilico', '204.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (205, 'Ganchos toalla', 'Set ganchos adhesivos potentes', 6.00, 'Metal', '205.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (206, 'Toallero barra', 'Toallero doble barra', 25.00, 'Inox', '206.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (207, 'Cajas ordenación', 'Cajas apilables traslúcidas', 10.00, 'Plastico', '207.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (208, 'Organizador maquillaje', 'Torre metacrilato maquillaje', 28.00, 'Glam', '208.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (209, 'Portarrollos reserva', 'Soporte para 3 rollos papel', 14.00, 'Metal', '209.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (210, 'Organizador cajón baño', 'Separadores para peines y cremas', 12.00, 'Plastico', '210.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (211, 'Discos aroma inodoro', 'Discos gel adhesivos WC', 5.00, 'Fresco', '211.jpg', 6);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (212, 'Bañera bebés', 'Bañera plástico ergonómica', 30.00, 'Infantil', '212.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (213, 'Termómetro baño', 'Juguete termómetro flotante', 8.00, 'Divertido', '213.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (214, 'Toalla capa bebé', 'Toalla con capucha animales', 15.00, 'Suave', '214.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (215, 'Juguetes baño', 'Set patitos y barcos goma', 12.00, 'Juego', '215.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (216, 'Asiento baño', 'Asiento seguridad ventosas', 22.00, 'Seguridad', '216.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (217, 'Alfombrilla bañera', 'Alfombra antideslizante infantil', 14.00, 'Seguridad', '217.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (218, 'Cambiador hinchable', 'Cambiador viaje impermeable', 18.00, 'Practico', '218.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (219, 'Taburete escalón', 'Taburete para alcanzar lavabo', 10.00, 'Funcional', '219.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (220, 'Orinal infantil', 'Orinal aprendizaje con música', 25.00, 'Motivador', '220.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (221, 'Cesta productos bebé', 'Cesta para geles y cremas', 16.00, 'Organizacion', '221.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (222, 'Ducha exterior jardín', 'Ducha conexión manguera', 80.00, 'Verano', '222.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (223, 'Hamaca piscina', 'Tumbona plegable aluminio', 65.00, 'Relax', '223.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (224, 'Set spa hinchable', 'Jacuzzi hinchable 2 personas', 350.00, 'Lujo', '224.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (225, 'Inodoro portátil', 'WC químico camping', 90.00, 'Camping', '225.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (226, 'Banco vestuario', 'Banco composite exterior', 70.00, 'Resistente', '226.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (227, 'Tendedero exterior', 'Tendedero paraguas aluminio', 50.00, 'Funcional', '227.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (228, 'Calefactor exterior', 'Estufa infrarrojos terraza', 120.00, 'Calido', '228.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (229, 'Parasol playa', 'Sombrilla protección UV', 30.00, 'Verano', '229.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (230, 'Panel privacidad', 'Biombo separador jardín', 60.00, 'Privacidad', '230.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (231, 'Cojines impermeables', 'Pack cojines silla exterior', 25.00, 'Resistente', '231.jpg', 8);
