INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (232, 'Sofá pequeño', 'Sofá 2 plazas compacto', 350.00, 'Nordico', '232.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (233, 'Sillón relax', 'Sillón orejero cómodo', 180.00, 'Clasico', '233.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (234, 'Mesa de centro', 'Mesa baja madera y metal', 90.00, 'Industrial', '234.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (235, 'Vitrina salón', 'Vitrina expositora cristal', 250.00, 'Rustico', '235.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (236, 'Mesa extensible', 'Mesa comedor extensible', 200.00, 'Funcional', '236.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (237, 'Banco salón', 'Banco madera entrada o salón', 70.00, 'Minimalista', '237.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (238, 'Mesa auxiliar', 'Mesita lateral sofá', 45.00, 'Moderno', '238.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (239, 'Consola lateral', 'Mueble recibidor estrecho', 110.00, 'Elegante', '239.jpg', 2);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (240, 'Lámpara mesa auxiliar', 'Lámpara cerámica sobremesa', 35.00, 'Ceramica', '240.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (241, 'Apliques pared', 'Luz indirecta pared', 25.00, 'Minimalista', '241.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (242, 'Lámpara decorativa', 'Lámpara diseño escultórico', 50.00, 'Vanguardista', '242.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (243, 'Focos riel', 'Sistema focos orientables', 40.00, 'Industrial', '243.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (244, 'Luz control remoto', 'Bombilla inteligente RGB', 18.00, 'Tecnologico', '244.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (245, 'Tiras LED TV', 'Retroiluminación para TV', 15.00, 'Moderno', '245.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (246, 'Luz ambiental', 'Lámpara suelo esfera', 60.00, 'Zen', '246.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (247, 'Luz lectura pie', 'Lámpara pie focalizada', 45.00, 'Funcional', '247.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (248, 'Lámpara de pie arco', 'Lámpara arco salón', 85.00, 'Diseno', '248.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (249, 'Lámpara techo araña', 'Lámpara colgante múltiples brazos', 95.00, 'Vintage', '249.jpg', 1);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (250, 'Set cuadros salón', 'Composición cuadros láminas', 40.00, 'Abstracto', '250.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (251, 'Espejo redondo', 'Espejo pared decorativo', 55.00, 'Boho', '251.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (252, 'Reloj estación', 'Reloj pared doble cara', 30.00, 'Retro', '252.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (253, 'Jarrones vidrio', 'Jarrón cristal reciclado', 20.00, 'Ecologico', '253.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (254, 'Escultura metal', 'Figura decorativa metal', 28.00, 'Industrial', '254.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (255, 'Tapiz macramé', 'Tapiz pared tejido', 35.00, 'Boho', '255.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (256, 'Centro de mesa', 'Fuente decorativa mesa', 25.00, 'Clasico', '256.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (257, 'Objeto escultórico', 'Pieza arte abstracto', 45.00, 'Moderno', '257.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (258, 'Planta grande', 'Ficus artificial maceta', 60.00, 'Natural', '258.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (259, 'Portafotos múltiple', 'Marco para varias fotos', 15.00, 'Familiar', '259.jpg', 3);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (260, 'Alfombra salón', 'Alfombra grande lana', 120.00, 'Calido', '260.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (261, 'Cojines sofá', 'Pack 2 cojines terciopelo', 25.00, 'Elegante', '261.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (262, 'Manta sofá', 'Manta tricotada suave', 30.00, 'Confort', '262.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (263, 'Cortinas salón', 'Cortinas largas lino', 50.00, 'Natural', '263.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (264, 'Visillos', 'Cortina translúcida blanca', 20.00, 'Luminoso', '264.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (265, 'Funda sofá', 'Funda elástica ajustable', 40.00, 'Practico', '265.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (266, 'Funda sillón', 'Cubre sillón acolchado', 25.00, 'Proteccion', '266.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (267, 'Tapete mesa', 'Camino mesa elegante', 15.00, 'Clasico', '267.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (268, 'Fundas cojines', 'Fundas recambio estampadas', 12.00, 'Variado', '268.jpg', 4);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (269, 'Cestas almacenaje', 'Juego 3 cestas mimbre', 35.00, 'Rustico', '269.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (270, 'Soporte altavoces', 'Pie metálico altavoz', 25.00, 'Industrial', '270.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (271, 'Organizador mandos', 'Soporte mandos sofá', 10.00, 'Practico', '271.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (272, 'Organizador vajilla', 'Separadores fieltro platos', 8.00, 'Proteccion', '272.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (273, 'Mueble bar', 'Carrito o mueble para licores', 90.00, 'Vintage', '273.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (274, 'Organizador cables', 'Caja esconder cables', 12.00, 'Minimalista', '274.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (275, 'Estantes flotantes', 'Set 3 baldas pared', 30.00, 'Nordico', '275.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (276, 'Organizador juegos', 'Torre almacenamiento consolas', 25.00, 'Gamer', '276.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (277, 'Librería', 'Estantería libros alta', 120.00, 'Clasico', '277.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (278, 'Cajas estantería', 'Cajas tela compatibles Kallax', 8.00, 'Colorido', '278.jpg', 5);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (279, 'Difusor salón', 'Difusor varillas gran formato', 25.00, 'Elegante', '279.jpg', 6);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (280, 'Alfombra juegos', 'Alfombra puzzle goma eva', 25.00, 'Infantil', '280.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (281, 'Parque bebé', 'Corralito plegable viaje', 60.00, 'Seguridad', '281.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (282, 'Baúl juguetes', 'Caja madera juguetes', 40.00, 'Orden', '282.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (283, 'Cojines bebé', 'Cojines formas animales', 15.00, 'Divertido', '283.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (284, 'Protector esquinas', 'Esquineras silicona muebles', 5.00, 'Seguridad', '284.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (285, 'Cesta juguetes', 'Cesta tela juguetes salón', 18.00, 'Decorativo', '285.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (286, 'Estantería baja', 'Librería Montessori accesible', 45.00, 'Montessori', '286.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (287, 'Hamaca bebé', 'Trona o hamaca reclinable', 55.00, 'Confort', '287.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (288, 'Túnel gateo', 'Juguete túnel plegable', 20.00, 'Actividad', '288.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (289, 'Manta actividades', 'Gimnasio bebé suelo', 35.00, 'Estimulacion', '289.jpg', 7);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (290, 'Sofás exterior', 'Conjunto sofás terraza', 250.00, 'Relax', '290.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (291, 'Mesa terraza', 'Mesa café exterior', 60.00, 'Metal', '291.jpg', 8);
INSERT INTO products (id, name, description, price, style, image, category_id) VALUES (292, 'Sillas jardín', 'Sillas apilables exterior', 40.00, 'Practico', '292.jpg', 8);
